#!/usr/bin/env bash
# The version string lives in five hand-edited manifests, again in the lockfile
# npm generates from the first of them, and again in the changelog, and nothing
# kept them in step. A release that bumps four of the five ships a plugin whose
# reported version disagrees with the marketplace entry that installed it —
# visible to users, invisible in review.
#
# The lockfile is checked here because it fails differently. It is not edited by
# hand but regenerated by `npm install --package-lock-only`, so the way to get it
# wrong is to skip that step rather than to miss a file, and nothing downstream
# complains: `npm ci` was measured against a lockfile whose root version
# disagreed with its package.json and installed it without a word, exit 0. So
# the whole cost of getting this wrong is a tracked, shipped file reporting the
# version of the previous release — which is this suite's own subject, and not a
# build failure someone else would catch first.
#
# Only the lockfile's root `version` is compared. npm writes it and
# `packages[""].version` in the same pass, so a second row cannot catch a
# skipped regeneration that the first row missed, and it would be the only path
# here needing an empty split segment to reach npm's key for the root package.
set -uo pipefail
# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

echo "version:"

# Reads a dotted path out of a JSON file. Array indices are plain integers:
# JS object access on an array accepts them.
read_json() {
  node -e '
    const o = require(process.argv[1]);
    let v = o;
    for (const k of process.argv[2].split(".")) v = v == null ? v : v[k];
    console.log(v == null ? "" : v);
  ' "$1" "$2" 2>/dev/null
}

MANIFESTS=(
  # Edited by hand at release time.
  "package.json|version"
  ".claude-plugin/plugin.json|version"
  ".claude-plugin/marketplace.json|plugins.0.version"
  ".codex-plugin/plugin.json|version"
  ".agents/plugins/marketplace.json|plugins.0.version"
  # Generated by npm, never edited.
  "package-lock.json|version"
)

# Compares one dotted path against REF and prints one result line. It is a
# function rather than the body of the loop below so that the mismatch check at
# the end drives the same code the release check does: a second copy could go on
# agreeing with the manifests after this one had stopped comparing anything.
check_version() { # check_version <label> <abs-path> <dotted-path>
  local label="$1" file="$2" path="$3" got
  got=$(read_json "$file" "$path")
  if [ "$got" = "$REF" ]; then
    printf 'ok   %s %s is %s\n' "$label" "$path" "$REF"
  else
    printf 'FAIL %s %s has %s, package.json has %s\n' "$label" "$path" "${got:-<missing>}" "$REF"
  fi
}

# Shared SemVer grammar (semver.org grammar, ERE form) so the manifest check
# and the changelog-heading check can never drift apart the way they did
# before: a prerelease/build version like 0.2.0-beta.1 must match both.
SEMVER_CORE='(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)'
SEMVER_PRERELEASE='(-((0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*))?'
SEMVER_BUILD='(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?'
SEMVER_RE="^${SEMVER_CORE}${SEMVER_PRERELEASE}${SEMVER_BUILD}\$"

REF=$(read_json "$ROOT/package.json" version)
if [[ "$REF" =~ $SEMVER_RE ]]; then
  PASS=$((PASS + 1)); printf '  ok   package.json carries a semver version (%s)\n' "$REF"
else
  FAIL=$((FAIL + 1)); printf '  FAIL package.json version is not semver: %s\n' "${REF:-<missing>}"
fi

for entry in "${MANIFESTS[@]}"; do
  file=${entry%%|*}
  path=${entry#*|}
  line=$(check_version "$file" "$ROOT/$file" "$path")
  case $line in
    ok*) PASS=$((PASS + 1)) ;;
    *)   FAIL=$((FAIL + 1)) ;;
  esac
  printf '  %s\n' "$line"
done

# Every row above runs against a repository whose manifests already agree, so
# none of them entered the branch that reports a disagreement — this suite going
# green over an unexercised comparison is the same blind spot it exists to close,
# one level up. Drive the same function against a version that deliberately
# disagrees, so a comparison that stopped comparing is caught here rather than at
# the release it was written for.
# The name is load-bearing, and the first draft of this check got it wrong:
# read_json calls `require`, which chooses its parser from the extension, so a
# bare mktemp file throws and the read comes back empty — indistinguishable from
# a version that disagrees. It reported FAIL for the wrong reason and the
# assertion below caught it.
STALE_DIR=$(mktemp -d)
printf '{"name":"revloop","version":"0.0.0-stale","lockfileVersion":3}\n' > "$STALE_DIR/package-lock.json"
STALE_LINE=$(check_version 'synthetic lockfile' "$STALE_DIR/package-lock.json" version)
expect "a disagreeing version is reported as a failure" "$STALE_LINE" 'FAIL'
expect "and the line names the version it found" "$STALE_LINE" '0.0.0-stale'
MISSING_LINE=$(check_version 'synthetic lockfile' "$STALE_DIR/package-lock.json" nosuchkey)
expect "an absent path is reported as missing, not as agreement" "$MISSING_LINE" '<missing>'
rm -rf "$STALE_DIR"

# The changelog's newest RELEASED heading, ignoring [Unreleased]. Before the
# first release there is none, and that is not a failure — it is the state the
# repository is in until a version is cut. Uses the same SEMVER_* grammar as
# REF above, so a prerelease/build heading like [0.2.0-beta.1] is recognized
# instead of silently falling through to "no release heading found".
CL=$(grep -oE "^## \[${SEMVER_CORE}${SEMVER_PRERELEASE}${SEMVER_BUILD}\]" "$ROOT/CHANGELOG.md" | head -1 | tr -d '#[] ')
if [ -z "$CL" ]; then
  printf '  note CHANGELOG.md has no released version heading yet; nothing to compare\n'
elif [ "$CL" = "$REF" ]; then
  PASS=$((PASS + 1)); printf '  ok   CHANGELOG.md newest release is %s\n' "$CL"
else
  FAIL=$((FAIL + 1))
  printf '  FAIL CHANGELOG.md newest release is %s, manifests say %s\n' "$CL" "$REF"
fi

summary "version"
