#!/usr/bin/env bash
# The version string lives in five hand-edited manifests, again in the lockfile
# npm generates from the first of them, and again in the changelog, and nothing
# kept them in step. A release that bumps four of the five ships a plugin whose
# reported version disagrees with the marketplace entry that installed it —
# visible to users, invisible in review.
#
# The lockfile is checked here because it fails differently. It is not edited by
# hand but regenerated by `npm install --package-lock-only`, so the way to get it
# wrong is to skip that step rather than to miss a file, and nothing downstream
# complains: `npm ci` was measured against a lockfile whose root version
# disagreed with its package.json and installed it without a word, exit 0. So
# the whole cost of getting this wrong is a tracked, shipped file reporting the
# version of the previous release — which is this suite's own subject, and not a
# build failure someone else would catch first.
#
# Only the lockfile's root `version` is compared. npm writes it and
# `packages[""].version` in the same pass, so a second row cannot catch a
# skipped regeneration that the first row missed, and it would be the only path
# here needing an empty split segment to reach npm's key for the root package.
set -uo pipefail
# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

echo "version:"

# Reads a dotted path out of a JSON file. Array indices are plain integers:
# JS object access on an array accepts them.
#
# The exit status separates the two ways a read comes back empty, because they
# have different remedies and one message was printed for both: 0 means a value
# was read — possibly the empty string, for a path this file does not carry —
# and 2 means the file could not be loaded at all. `tests/validate-schema.mjs`
# splits its own exits the same way and for the same reason: a file nobody could
# open, reported as a file that disagreed, sends the reader to the wrong repair.
read_json() {
  node -e '
    let o;
    try { o = require(process.argv[1]); } catch { process.exit(2); }
    let v = o;
    for (const k of process.argv[2].split(".")) v = v == null ? v : v[k];
    console.log(v == null ? "" : v);
  ' "$1" "$2" 2>/dev/null
}

# Each row is file | dotted path | what to do when it disagrees. The remedy is
# in the row because it is not the same for every row and the message did not
# say so: five of these are edited by hand and the sixth must never be, and a
# line reading `FAIL package-lock.json version has 0.5.0` invites exactly the
# hand edit that leaves the rest of the lockfile behind.
MANIFESTS=(
  "package.json|version|edit this file"
  ".claude-plugin/plugin.json|version|edit this file"
  ".claude-plugin/marketplace.json|plugins.0.version|edit this file"
  ".codex-plugin/plugin.json|version|edit this file"
  ".agents/plugins/marketplace.json|plugins.0.version|edit this file"
  "package-lock.json|version|run npm install --package-lock-only; do not edit it"
)

# Compares one dotted path against REF, prints one result line, and RETURNS the
# verdict. It is a function rather than the body of the loop below so that the
# checks at the end drive the same code the release check does: a second copy
# could go on agreeing with the manifests after this one had stopped comparing
# anything. It returns rather than only printing because the loop classified on
# an `ok` prefix of a human-readable sentence, so rewording a message would have
# moved the PASS/FAIL counts with nothing to catch it.
check_version() { # check_version <label> <abs-path> <dotted-path> <remedy>
  local label="$1" file="$2" path="$3" remedy="$4" got rc
  got=$(read_json "$file" "$path"); rc=$?
  if [ "$rc" -ne 0 ]; then
    printf 'FAIL %s %s <unreadable> — the file could not be parsed as JSON\n' "$label" "$path"
    return 1
  fi
  # Without this, a package.json that does not parse leaves REF empty, and every
  # other file that also fails to yield a value compares equal to it and is
  # reported as agreeing. The suite still fails on the semver row above, so the
  # run is not lost — but the per-file lines point away from the broken file.
  if [ -z "$REF" ]; then
    printf 'FAIL %s %s not compared — package.json yielded no version to compare against\n' "$label" "$path"
    return 1
  fi
  if [ "$got" = "$REF" ]; then
    printf 'ok   %s %s is %s\n' "$label" "$path" "$REF"
    return 0
  fi
  printf 'FAIL %s %s has %s, package.json has %s — %s\n' \
    "$label" "$path" "${got:-<missing>}" "$REF" "$remedy"
  return 1
}

# Shared SemVer grammar (semver.org grammar, ERE form) so the manifest check
# and the changelog-heading check can never drift apart the way they did
# before: a prerelease/build version like 0.2.0-beta.1 must match both.
SEMVER_CORE='(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)'
SEMVER_PRERELEASE='(-((0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*))?'
SEMVER_BUILD='(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?'
SEMVER_RE="^${SEMVER_CORE}${SEMVER_PRERELEASE}${SEMVER_BUILD}\$"

REF=$(read_json "$ROOT/package.json" version); REF_RC=$?
if [ "$REF_RC" -ne 0 ]; then
  FAIL=$((FAIL + 1)); REF=''
  printf '  FAIL package.json could not be parsed as JSON; nothing below has a reference\n'
elif [[ "$REF" =~ $SEMVER_RE ]]; then
  PASS=$((PASS + 1)); printf '  ok   package.json carries a semver version (%s)\n' "$REF"
else
  FAIL=$((FAIL + 1)); printf '  FAIL package.json version is not semver: %s\n' "${REF:-<missing>}"
fi

for entry in "${MANIFESTS[@]}"; do
  IFS='|' read -r file path remedy <<< "$entry"
  if line=$(check_version "$file" "$ROOT/$file" "$path" "$remedy"); then
    PASS=$((PASS + 1))
  else
    FAIL=$((FAIL + 1))
  fi
  printf '  %s\n' "$line"
done

# Every row above runs against a repository whose manifests already agree, so
# none of them entered the branch that reports a disagreement — this suite going
# green over an unexercised comparison is the same blind spot it exists to close,
# one level up. The checks below drive the same function, and classify its
# result the same way the loop does rather than by reading its text, so a
# comparison that stopped comparing is caught here and not at the release it was
# written for.
#
# The synthetic file's NAME is load-bearing, and the first draft got it wrong:
# read_json calls `require`, which chooses its parser from the extension, so a
# bare mktemp file threw and the read came back empty — reported as a version
# that disagreed. That is the confusion the exit-status split above removes, and
# it is why the unreadable case is one of the four below.
STALE_DIR=$(mktemp -d)
trap 'rm -rf "$STALE_DIR"' EXIT
printf '{"name":"revloop","version":"0.0.0-stale","lockfileVersion":3}\n' > "$STALE_DIR/package-lock.json"
printf 'this is not JSON\n' > "$STALE_DIR/broken.json"

# Runs check_version and classifies it the way the release loop does — on the
# return status, never on the text — then leaves the line in SELF_LINE so the
# expect() calls beside each one can assert what it said.
classify() { # classify <label> <expected verdict: ok|fail> <check_version args...>
  local name="$1" want="$2" line rc
  shift 2
  line=$(check_version "$@"); rc=$?
  SELF_LINE="$line"
  if { [ "$want" = ok ] && [ "$rc" -eq 0 ]; } || { [ "$want" = fail ] && [ "$rc" -ne 0 ]; }; then
    PASS=$((PASS + 1)); printf '  ok   %s\n' "$name"
  else
    FAIL=$((FAIL + 1)); printf '  FAIL %s\n       got: %s\n' "$name" "$line"
  fi
}

classify "a disagreeing version is classified as a failure" fail \
  'synthetic lockfile' "$STALE_DIR/package-lock.json" version 'regenerate it'
expect "and the line names the version it found" "$SELF_LINE" '0.0.0-stale'
expect "and the line names the remedy for that file" "$SELF_LINE" 'regenerate it'

classify "an absent path is classified as a failure" fail \
  'synthetic lockfile' "$STALE_DIR/package-lock.json" nosuchkey 'regenerate it'
expect "and reads as missing rather than as a version" "$SELF_LINE" '<missing>'

classify "a file that is not JSON is classified as a failure" fail \
  'synthetic lockfile' "$STALE_DIR/broken.json" version 'regenerate it'
expect "and reads as unreadable rather than as missing" "$SELF_LINE" '<unreadable>'

classify "an absent file is classified as a failure" fail \
  'synthetic lockfile' "$STALE_DIR/gone.json" version 'regenerate it'
expect "and reads as unreadable rather than as a mismatch" "$SELF_LINE" '<unreadable>'

# An agreeing value must still classify as agreement, or every row above would
# pass by never returning zero.
classify "an agreeing version is classified as agreement" ok \
  'this package.json' "$ROOT/package.json" version 'edit this file'

# The changelog's newest RELEASED heading, ignoring [Unreleased]. Before the
# first release there is none, and that is not a failure — it is the state the
# repository is in until a version is cut. Uses the same SEMVER_* grammar as
# REF above, so a prerelease/build heading like [0.2.0-beta.1] is recognized
# instead of silently falling through to "no release heading found".
CL=$(grep -oE "^## \[${SEMVER_CORE}${SEMVER_PRERELEASE}${SEMVER_BUILD}\]" "$ROOT/CHANGELOG.md" | head -1 | tr -d '#[] ')
if [ -z "$CL" ]; then
  printf '  note CHANGELOG.md has no released version heading yet; nothing to compare\n'
elif [ "$CL" = "$REF" ]; then
  PASS=$((PASS + 1)); printf '  ok   CHANGELOG.md newest release is %s\n' "$CL"
else
  FAIL=$((FAIL + 1))
  printf '  FAIL CHANGELOG.md newest release is %s, manifests say %s\n' "$CL" "$REF"
fi

summary "version"
