#!/usr/bin/env bash
# The version string lives in five hand-edited manifests, again in the lockfile
# npm generates from the first of them, and again in the changelog, and nothing
# kept them in step. A release that bumps four of the five ships a plugin whose
# reported version disagrees with the marketplace entry that installed it —
# visible to users, invisible in review.
#
# The lockfile is checked here because it fails differently. It is not edited by
# hand but regenerated by `npm install --package-lock-only`, so the way to get it
# wrong is to skip that step rather than to miss a file, and nothing downstream
# complains: `npm ci` was measured against a lockfile whose root version
# disagreed with its package.json and installed it without a word, exit 0. So
# the whole cost of getting this wrong is a tracked, shipped file reporting the
# version of the previous release — which is this suite's own subject, and not a
# build failure someone else would catch first.
#
# Only the lockfile's root `version` is compared. npm writes it and
# `packages[""].version` in the same pass, so a second row cannot catch a
# skipped regeneration that the first row missed, and it would be the only path
# here needing an empty split segment to reach npm's key for the root package.
set -uo pipefail
# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

echo "version:"

# Reads a dotted path out of a JSON file. Array indices are plain integers:
# JS object access on an array accepts them.
#
# The exit status separates the ways a read comes back empty, because each sends
# the reader somewhere different and one message was printed for all of them: 0
# is a value — possibly the empty string, for a path this file does not carry —
# 3 is no such file, 2 is a file that is not valid JSON, and 4 is every other way
# the read can fail. A renamed manifest reported as a syntax error sends somebody
# to look for a stray comma in a file that is not there, and a file that could
# not be opened does the same.
#
# `tests/validate-schema.mjs` makes a coarser split for a related reason and is
# not a precedent for the shape of this one: its 1-versus-2 separates "it said
# no" from "it never ran", and it merges an absent file with an unparseable one
# into the second. This is the same principle — a non-answer is not an answer —
# applied one level finer.
#
# stderr is discarded, so 4 carries no detail. The words it prints say that
# rather than naming a cause it does not have.
read_json() {
  node -e '
    let o;
    try { o = require(process.argv[1]); }
    catch (e) {
      if (e && e.code === "MODULE_NOT_FOUND") process.exit(3);
      process.exit(e instanceof SyntaxError ? 2 : 4);
    }
    let v = o;
    for (const k of process.argv[2].split(".")) v = v == null ? v : v[k];
    console.log(v == null ? "" : v);
  ' "$1" "$2" 2>/dev/null
}

# Maps that status onto the words a reader acts on. It is shared because the
# reference read below and check_version printed different words for the same
# status, and the coarser pair was on the reference read — the one every other
# row depends on.
read_status_words() { # read_status_words <rc>
  case $1 in
    3) printf '<absent> — there is no such file' ;;
    2) printf '<unreadable> — it is not valid JSON' ;;
    *) printf '<unreadable> — reading it failed some other way; stderr is discarded' ;;
  esac
}

# Each row is file | dotted path | what to do when it disagrees. The remedy is
# in the row because it is not the same for every row and the message did not
# say so: five of these are edited by hand and the sixth must never be, and a
# line reading `FAIL package-lock.json version has 0.5.0` invites exactly the
# hand edit that leaves the rest of the lockfile behind.
#
# A remedy may not contain a literal `|`. The rows are pipe-delimited, so one
# that did would split into a fourth field and be rejected as malformed — which
# is the safe direction, and the message says so rather than reporting a typo
# the writer did not make.
MANIFESTS=(
  "package.json|version|edit this file"
  ".claude-plugin/plugin.json|version|edit this file"
  ".claude-plugin/marketplace.json|plugins.0.version|edit this file"
  ".codex-plugin/plugin.json|version|edit this file"
  ".agents/plugins/marketplace.json|plugins.0.version|edit this file"
  "package-lock.json|version|run npm install --package-lock-only; do not edit it"
)

# Splits one row and says whether it is well formed. A function because the loop
# below and the checks at the end must agree about what a malformed row is, and
# because a guard nothing drives is the branch this file exists to object to.
parse_row() { # parse_row <entry> ; sets ROW_FILE ROW_PATH ROW_REMEDY
  local extra
  IFS='|' read -r ROW_FILE ROW_PATH ROW_REMEDY extra <<< "$1"
  [ -n "$ROW_FILE" ] && [ -n "$ROW_PATH" ] && [ -n "$ROW_REMEDY" ] && [ -z "$extra" ]
}

# Compares one dotted path against a reference, prints one result line, and
# RETURNS the verdict. The reference is an argument rather than the global it
# used to read, so the empty-reference guard below can be driven with one — a
# subshell assignment could do it and shellcheck is right that a value set that
# way is lost, which is the same class of mistake as the guard itself.
#
# It is a function rather than the body of the loop below so that the
# checks at the end drive the same code the release check does: a second copy
# could go on agreeing with the manifests after this one had stopped comparing
# anything. It returns rather than only printing because the loop classified on
# an `ok` prefix of a human-readable sentence, so rewording a message would have
# moved the PASS/FAIL counts with nothing to catch it.
check_version() { # check_version <label> <abs-path> <dotted-path> <remedy> <reference>
  local label="$1" file="$2" path="$3" remedy="$4" REF="$5" got rc
  got=$(read_json "$file" "$path"); rc=$?
  if [ "$rc" -ne 0 ]; then
    printf 'FAIL %s %s %s\n' "$label" "$path" "$(read_status_words "$rc")"
    return 1
  fi
  # Without this, a package.json that does not parse leaves REF empty, and every
  # other file that also fails to yield a value compares equal to it and is
  # reported as agreeing. The suite still fails on the semver row above, so the
  # run is not lost — but the per-file lines point away from the broken file.
  if [ -z "$REF" ]; then
    printf 'FAIL %s %s not compared — package.json yielded no version to compare against\n' "$label" "$path"
    return 1
  fi
  if [ "$got" = "$REF" ]; then
    printf 'ok   %s %s is %s\n' "$label" "$path" "$REF"
    return 0
  fi
  printf 'FAIL %s %s has %s, package.json has %s — %s\n' \
    "$label" "$path" "${got:-<missing>}" "$REF" "$remedy"
  return 1
}

# Shared SemVer grammar (semver.org grammar, ERE form) so the manifest check
# and the changelog-heading check can never drift apart the way they did
# before: a prerelease/build version like 0.2.0-beta.1 must match both.
SEMVER_CORE='(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)'
SEMVER_PRERELEASE='(-((0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*))?'
SEMVER_BUILD='(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?'
SEMVER_RE="^${SEMVER_CORE}${SEMVER_PRERELEASE}${SEMVER_BUILD}\$"

REF=$(read_json "$ROOT/package.json" version); REF_RC=$?
if [ "$REF_RC" -ne 0 ]; then
  FAIL=$((FAIL + 1)); REF=''
  printf '  FAIL package.json %s; nothing below has a reference\n' "$(read_status_words "$REF_RC")"
elif [[ "$REF" =~ $SEMVER_RE ]]; then
  PASS=$((PASS + 1)); printf '  ok   package.json carries a semver version (%s)\n' "$REF"
else
  FAIL=$((FAIL + 1)); printf '  FAIL package.json version is not semver: %s\n' "${REF:-<missing>}"
fi

for entry in "${MANIFESTS[@]}"; do
  if ! parse_row "$entry"; then
    FAIL=$((FAIL + 1))
    printf '  FAIL malformed MANIFESTS row — three fields, and no "|" inside one: %s\n' "$entry"
    continue
  fi
  file=$ROW_FILE path=$ROW_PATH remedy=$ROW_REMEDY
  if line=$(check_version "$file" "$ROOT/$file" "$path" "$remedy" "$REF"); then
    PASS=$((PASS + 1))
  else
    FAIL=$((FAIL + 1))
  fi
  printf '  %s\n' "$line"
done

# Every row above runs against a repository whose manifests already agree, so
# none of them entered the branch that reports a disagreement — this suite going
# green over an unexercised comparison is the same blind spot it exists to close,
# one level up. The checks below drive the same function, and classify its
# result the same way the loop does rather than by reading its text, so a
# comparison that stopped comparing is caught here and not at the release it was
# written for.
#
# The synthetic file's NAME is load-bearing, and the first draft got it wrong:
# read_json calls `require`, which chooses its parser from the extension, so a
# bare mktemp file threw and the read came back empty — reported as a version
# that disagreed. That is the confusion the exit-status split above removes, and
# it is why the unreadable case is one of the four below.
STALE_DIR=$(mktemp -d)
trap 'rm -rf "$STALE_DIR"' EXIT
printf '{"name":"revloop","version":"0.0.0-stale","lockfileVersion":3}\n' > "$STALE_DIR/package-lock.json"
printf 'this is not JSON\n' > "$STALE_DIR/broken.json"

# Runs check_version and classifies it the way the release loop does — on the
# return status, never on the text — then leaves the line in SELF_LINE so the
# expect() calls beside each one can assert what it said.
classify() { # classify <label> <expected verdict: ok|fail> <check_version args...>
  local name="$1" want="$2" line rc
  shift 2
  line=$(check_version "$@"); rc=$?
  SELF_LINE="$line"
  local verdict=ok; [ "$rc" -eq 0 ] || verdict=fail
  if [ "$verdict" = "$want" ]; then
    PASS=$((PASS + 1)); printf '  ok   %s\n' "$name"
  else
    FAIL=$((FAIL + 1)); printf '  FAIL %s\n       got: %s\n' "$name" "$line"
  fi
}

classify "a disagreeing version is classified as a failure" fail \
  'synthetic lockfile' "$STALE_DIR/package-lock.json" version 'regenerate it' "$REF"
expect "and the line names the version it found" "$SELF_LINE" '0.0.0-stale'
expect "and the line names the remedy for that file" "$SELF_LINE" 'regenerate it'

classify "an absent path is classified as a failure" fail \
  'synthetic lockfile' "$STALE_DIR/package-lock.json" nosuchkey 'regenerate it' "$REF"
expect "and reads as missing rather than as a version" "$SELF_LINE" '<missing>'

classify "a file that is not JSON is classified as a failure" fail \
  'synthetic lockfile' "$STALE_DIR/broken.json" version 'regenerate it' "$REF"
expect "and reads as unreadable rather than as missing" "$SELF_LINE" '<unreadable>'

classify "an absent file is classified as a failure" fail \
  'synthetic lockfile' "$STALE_DIR/gone.json" version 'regenerate it' "$REF"
expect "and reads as absent rather than as unparseable" "$SELF_LINE" '<absent>'

# The guard that refuses an empty reference, driven with the reference empty and
# the read also empty — which is the only state where its absence would matter,
# because "" = "" is the comparison that reports a broken file as agreeing.
classify "an empty reference is classified as a failure, not as agreement" fail \
  'synthetic lockfile' "$STALE_DIR/package-lock.json" nosuchkey 'regenerate it' ''
expect "and names the reference as what is missing" "$SELF_LINE" 'package.json yielded no version'

# An agreeing value must still classify as agreement, or every row above would
# pass by never returning zero.
classify "an agreeing version is classified as agreement" ok \
  'this package.json' "$ROOT/package.json" version 'edit this file' "$REF"

# The lockfile's remedy is the one string in MANIFESTS that exists to stop an
# action rather than to describe one, so it is asserted as literal text. That is
# a deliberate second copy: a test that read the row's own value would pass over
# any typo in it, and a typo in this string is a line nobody would look at twice.
LOCK_REMEDY='run npm install --package-lock-only; do not edit it'
expect "the lockfile row still carries the remedy that forbids a hand edit" \
  "${MANIFESTS[*]}" "$LOCK_REMEDY"
classify "and a disagreeing lockfile is classified as a failure" fail \
  'synthetic lockfile' "$STALE_DIR/package-lock.json" version "$LOCK_REMEDY" "$REF"
expect "and its line carries that remedy through to the reader" "$SELF_LINE" "$LOCK_REMEDY"

# Exit 4 is read_json's catch-all and the reachable instance of it is a file that
# is there and cannot be opened. As root there is no such file, so this says it
# did not run rather than passing over a case it never built.
if [ "$(id -u)" -ne 0 ]; then
  printf '{"version":"0.0.0-stale"}\n' > "$STALE_DIR/locked.json"
  chmod 000 "$STALE_DIR/locked.json"
  classify "a file that cannot be opened is classified as a failure" fail \
    'synthetic lockfile' "$STALE_DIR/locked.json" version "$LOCK_REMEDY" "$REF"
  refute "and is not reported as a syntax error it was never read for" "$SELF_LINE" 'not valid JSON'
  chmod 644 "$STALE_DIR/locked.json"
else
  printf '  note running as root; a file that cannot be opened cannot be constructed\n'
fi

# The row guard, which nothing above drives: every real row is well formed, so
# its rejecting branch had the same no-coverage problem the comparison had.
for bad in 'a.json|version' 'a.json' '|version|edit this file' 'a.json||edit this file' \
  'a.json|version|do not use | inside a remedy'; do
  if parse_row "$bad"; then
    FAIL=$((FAIL + 1)); printf '  FAIL a malformed row was accepted: %s\n' "$bad"
  else
    PASS=$((PASS + 1)); printf '  ok   a malformed row is rejected: %s\n' "$bad"
  fi
done
if parse_row 'a.json|version|edit this file'; then
  PASS=$((PASS + 1)); printf '  ok   a well-formed row is accepted\n'
else
  FAIL=$((FAIL + 1)); printf '  FAIL a well-formed row was rejected\n'
fi

# The changelog's newest RELEASED heading, ignoring [Unreleased]. Before the
# first release there is none, and that is not a failure — it is the state the
# repository is in until a version is cut. Uses the same SEMVER_* grammar as
# REF above, so a prerelease/build heading like [0.2.0-beta.1] is recognized
# instead of silently falling through to "no release heading found".
CL=$(grep -oE "^## \[${SEMVER_CORE}${SEMVER_PRERELEASE}${SEMVER_BUILD}\]" "$ROOT/CHANGELOG.md" | head -1 | tr -d '#[] ')
if [ -z "$CL" ]; then
  printf '  note CHANGELOG.md has no released version heading yet; nothing to compare\n'
elif [ "$CL" = "$REF" ]; then
  PASS=$((PASS + 1)); printf '  ok   CHANGELOG.md newest release is %s\n' "$CL"
else
  FAIL=$((FAIL + 1))
  printf '  FAIL CHANGELOG.md newest release is %s, manifests say %s\n' "$CL" "$REF"
fi

summary "version"
